/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author tamara
 */
public class StockWareHouse extends javax.swing.JFrame {
  private static Connection con = null;
  private ResultSet rs;
  private PreparedStatement st;
    private Connection c;
    DefaultTableModel mdlTabla;
    /**
     * Creates new form StockWareHouse
     */
    public StockWareHouse() {
        initComponents();
        leerdatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelBuscar = new javax.swing.JLabel();
        cmbBusqueda = new javax.swing.JComboBox<>();
        txtTermino = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListaPr = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelBuscar.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        labelBuscar.setText("Buscar por");

        cmbBusqueda.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        cmbBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Producto", "Categ" }));

        txtTermino.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTermino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTerminoActionPerformed(evt);
            }
        });

        tableListaPr.setBorder(new javax.swing.border.MatteBorder(null));
        tableListaPr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PRODUCTO", "CANTIDAD", "CATEGORIA", "PRECIO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableListaPr);

        btnBuscar.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("      STOCK DEL ALMACÉN ");

        btnNuevo.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        btnNuevo.setText("Insertar/Modificar");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnVentas.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(226, 226, 226))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(btnVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(265, 265, 265))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBuscar)
                    .addComponent(cmbBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(btnVentas))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTerminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTerminoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTerminoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        buscarproducto(cmbBusqueda.getSelectedItem().toString(), txtTermino.getText(), tableListaPr);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        Stockventana nuevo = new Stockventana();
        nuevo.stockVentana();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        // TODO add your handling code here:
        ventasVentana ventas = new ventasVentana();
        ventas.ventanaNueva();
    }//GEN-LAST:event_btnVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockWareHouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockWareHouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockWareHouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockWareHouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockWareHouse().setVisible(true);
            }
        });
    }
        private void leerdatos(){
            
         try {
             con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mercado_espanol?&user=root&password=Pasword123"
                     + "&useLegacyDatetimeCode=false&serverTimezone=UTC");
             
             String sql = "SELECT id,producto,cantidad,categ,precio FROM productos;";
             
             Statement statement = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
             
             rs = statement.executeQuery(sql);
             
             JOptionPane.showMessageDialog(null, "Conexión establecida");
             
         } catch (SQLException ex) {
             Logger.getLogger(Stockventana.class.getName()).log(Level.SEVERE, null, ex);
         }
        
    }
        
private void buscarproducto(String thing, String product, JTable tabla){
                  
        String [] columnas = {"id", "producto","cantidad", "categoria", "precio"};
        String [] registros = new String [5];
        mdlTabla = new DefaultTableModel(null, columnas);
        
        c=null;
        String sql; 
        
        
         try {
             
             if (thing.equalsIgnoreCase("producto")) {
                 
             
             sql= "SELECT id, producto, cantidad, categ, precio FROM productos WHERE producto LIKE '%" + product + "%'";
             
             c = DriverManager.getConnection("jdbc:mysql://localhost:3306/mercado_espanol?&user=root&password=Pasword123"
                     + "&useLegacyDatetimeCode=false&serverTimezone=UTC");
                       
             st = c.prepareStatement(sql);
             
             ResultSet rrs= st.executeQuery();
             
             while (rrs.next()) {
                 registros[0] = rrs.getString("id");
                 registros[1] = rrs.getString("producto");
                 registros[2] = rrs.getString("cantidad");
                 registros[3] = rrs.getString("categ");
                 registros[4] = rrs.getString("precio");
                 
                 mdlTabla.addRow(registros);
                 
                 }
             
             
             }   if (thing.equalsIgnoreCase("categ")) {
                 
             sql= "SELECT id, producto, cantidad, categ, precio FROM productos WHERE categ LIKE '%" + product + "%'";                      
             c = DriverManager.getConnection("jdbc:mysql://localhost:3306/mercado_espanol?&user=root&password=Pasword123"
                     + "&useLegacyDatetimeCode=false&serverTimezone=UTC"); 
             
             st = c.prepareStatement(sql);
             
             ResultSet rrs= st.executeQuery();
             
             while (rrs.next()) {
                 registros[0] = rrs.getString("id");
                 registros[1] = rrs.getString("producto");
                 registros[2] = rrs.getString("cantidad");
                 registros[3] = rrs.getString("categ");
                 registros[4] = rrs.getString("precio");
                 
                 mdlTabla.addRow(registros);
             }
             } 
             
             tableListaPr.setModel(mdlTabla);
             c=null;
             
         } catch (SQLException ex) {
             Logger.getLogger(ventasVentana.class.getName()).log(Level.SEVERE, null, ex);
         }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnVentas;
    private javax.swing.JComboBox<String> cmbBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBuscar;
    private javax.swing.JTable tableListaPr;
    private javax.swing.JTextField txtTermino;
    // End of variables declaration//GEN-END:variables
}
